#!/bin/sh

# clj - Clojure launcher script

#!/bin/sh
BREAK_CHARS="\(\){}[],^%\$#@\"\";:''|\\"
CLOJURE_DIR=/usr/local/Cellar/clojure/1.4.0
CLOJURE_JAR="$CLOJURE_DIR"/clojure-1.4.0.jar
if [ $# -eq 0 ]; then 
     exec rlwrap --remember -c -b "$BREAK_CHARS" \
        -f "$HOME"/.clj_completions \
         java -cp "$CLOJURE_JAR" clojure.main
else
     exec java -cp "$CLOJURE_JAR" clojure.main $1 -- "$@"
fi

