#!/bin/bash
alias ..='cd ..'

alias ls='ls -h --color=auto'
[[ "$PLATFORM" == "mac" ]] && alias ls='gls -h --color=auto'
alias ll='ls -l'
alias lt='ll -t'
alias la='ll -a'
alias grep='grep --color=auto'
